services:
  zookeeper:
    image: zookeeper
    container_name: zookeeperV2
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafkaV2
    ports:
      - "9092:9092"

    depends_on:
      - zookeeper

    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181


  consumerapp:
    image: consumerimage
    container_name: kafkaconsumerV2
    ports:
      - "9292:9292"
    depends_on:
      - kafka


  producerapp:
    image: producerimage
    container_name: kafkaproducerV2
    ports:
      - "8080:8080"

    depends_on:
      - kafka
    environment:
      CONTAINER_ID: "kafkaproducerV2"